import type { AppState } from "../shared/types";

export const state: AppState = {
	query: "",
	draftQuery: "",
	searchText: "",
	showQuery: false,
	container: "",
	stream: "",
	severity: "",
	duration: "5m",
	live: true,
	sort: "desc",
	wrap: false,
	pageToken: "",
	entries: [],
	containers: [],
	response: null,
	loading: false,
	lastUpdated: "",
	tailConnected: false,
	tailMessage: "",
	selectedId: null,
	expandedFields: [],
	fieldsHidden: true,
	timelineHidden: false,
	timeFrom: "",
	timeTo: "",
	theme: "dark",
	navExpanded: false,
	errors: { status: "", explorer: "" },
	errorDetails: [],
};
